### ISSUE TITLE
Dev Container Integration.

### ISSUE THREAD

**Issue by huxuan** [serious-scaffold/ss-python#251]
TODO:

- [x] Multi-stage (prod and dev) Dockerfile (#263)
   - https://github.com/orgs/devcontainers/discussions/4#discussioncomment-4152158
   - https://github.com/microsoft/vscode-dev-containers/issues/304#issuecomment-1647101695 
   - https://pdm-project.org/latest/usage/advanced/#use-pdm-in-a-multi-stage-dockerfile
- [x] Pre-build images with GitHub Actions (#263)
   - https://containers.dev/guide/prebuild
- [x] Pre-build images with GitLab CI/CD (#263)
   - https://containers.dev/guide/gitlab-ci
- [x] Dev Container configuration with pre-build image (#281)
   - https://containers.dev/guide/dockerfile
- [x] Dev Container badge (#282)
   - https://code.visualstudio.com/docs/devcontainers/create-dev-container#_add-an-open-in-dev-container-badge
   - DevContainer Workflow badge.
- [x] Improve performance for .venv folder (#281)
   - https://code.visualstudio.com/remote/advancedcontainers/improve-performance
- [x] `make dev` as Post start command (#281)
   - https://code.visualstudio.com/remote/advancedcontainers/start-processes
- [ ] #280
   - https://code.visualstudio.com/remote/advancedcontainers/environment-variables
- [x] Config VSCode Extensions. (#281)
   - https://containers.dev/supporting#visual-studio-code
- [x] Trigger image built workflow only when changes happened in the prebuild devcontainer folder. (#263, #281)
   - Done for GitHub, depends on #264 for GitLab.
- [x] #277
- [x] Container Registry host adapted to GitHub and GitLab. (#290)
- [x] Support manually trigger of devcontainer prebuild. (#286)
- [ ] Documentation. (#305)

Dependencies:

- <del>The official DevContainer GitHub Actions lacks of build-args: https://github.com/devcontainers/ci/issues/270 </del>

NOTES:

- No use for features and templates, try to be as general as possible, considering the scenarios that dev containers is not used but a dev/prod container image is still needed.

References:

- https://code.visualstudio.com/docs/devcontainers/containers
- https://containers.dev/

**Comment by huxuan** [comment]
Closed as most of the tasks are done and those remaining (with external dependency) are tracked with separate issues.
