### ISSUE TITLE
Semantic Release

### ISSUE THREAD

**Issue by huxuan** [serious-scaffold/ss-python#549]
- [x] build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test 
   - [x] Configuration & GitHub (#550)
   - [x] GitLab (#553)
- [x] renovate update: https://semantic-release.gitbook.io/semantic-release/usage/installation#notes (#570)
- [x] Remove `git-changelog` relateted operations (#552)
- [x] Make renovate use `build` instead of `chore` (#560)
- [x] Fix error on GitLab: https://gitlab.com/serious-scaffold/ss-python/-/jobs/6886180792 (#565)
- [x] Update Documentation
   - [x] Repository Settings (#572)
   - [x] release process (#576)
   - [x] template and dependency update (#578)
   - [x] Features in README (#578)
   - [x] GitHub App / Token permission: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules#about-tag-protection-rules (#572)
   - [x] GitLab authentication (#559)
   - [x] GitHub authentication (#557)

**Comment by huxuan** [comment]
Hi @msclock 

After merging #578, seems all the subtasks for semantic-release are done. Do you have any other concern? Otherwise, maybe we can close this issue.

**Comment by msclock** [comment]
@huxuan Good job👍 Let's move forward.
